# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # Set default python version to 3.10
  - python=3.10
  # Everyone wants to use nbgitpuller for everything
  - nbgitpuller=1.1.*

  # ─────────────────────────────────────────────────────────────────────────────
  # Amazon Q Developer JupyterLab extension
  - amazon-q-developer-jupyterlab-ext
